pizzas/urls.py
from django.urls import path

from . import views

app_name = 'pizzas'

urlpatterns = [
    path('', views.index, name='index'),
    path('pizzas', views.pizzas, name="pizzas"),
    path('pizzas/<int:p_id>/', views.pizza, name="pizza"),
    path('new_comment/<int:pizza_id>/', views.new_comment, name="new_comment")
]

pizzas/models.py
from django.db import models

# Create your models here.


class Pizza(models.Model):
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)

    def __str__(self):
        return self.name


class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.TextField()

    def __str__(self):
        return f"{self.name[:50]}"


# class Comment(models.Model):
#     pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
#     name = models.TextField()

#     def __str__(self):
#         return f"{self.name[:100]}"

pizzas/forms.py
from django import forms
from .models import Pizza, Topping


class PizzaForm(forms.ModelForm):
    class Meta:
        model = Topping
        fields = ['name']
        labels = {'name': ''}
        widgets = {'name': forms.Textarea(attrs={'cols': 80})}

pizzas/views.py
from django.shortcuts import render, redirect
from .models import Pizza, Topping
from .forms import PizzaForm
# Create your views here.


def index(request):
    return render(request, 'pizzas/index.html')


def pizzas(request):
    pizzas = Pizza.objects.order_by('date_added')
    context = {'pizzas': pizzas}

    return render(request, 'pizzas/pizzas.html', context)


def pizza(request, p_id):
    pizza = Pizza.objects.get(id=p_id)
    toppings = pizza.topping_set.order_by('pizza_id')

    context = {'pizza': pizza, 'toppings': toppings}

    return render(request, 'pizzas/pizza.html', context)


def new_comment(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    if request.method != 'POST':
        form = PizzaForm()
    else:
        form = PizzaForm(data=request.POST)

        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.pizza = pizza
            new_comment.save()
            form.save()
            return redirect('pizzas:pizzas', pizza_id=pizza_id)

    context = {'form': form, 'pizza': pizza}
    return render(request, 'pizzas/new_comment.html', context)

pizzas/templates/pizzas/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
</head>

<body>
    <div class="navbar">
        <ul>
            <li class="links-home"><a class="pizzas" href="{% url 'pizzas:pizzas' %}">Our Pizzas</a></li>
            <li class="links"><a class="pizzeria" href="{% url 'pizzas:index' %}">Giovanni's Pizzeria</a></li>
        </ul>
    </div>
</body>

</html>


{% block content %} {% endblock content %}

pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}
{% load static %}

{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Pizzeria</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
</head>

<body>
    <img class="header" src="{% static '../static/images/header.jpeg' %}"">
    <div class=" header-title">
    <h1 class="store-title">Giovanni's Pizzeria</h1>
    <h3>Buy any pizza you want.</h3>
    </div>
</body>

</html>

{% endblock content %}

pizzas/templates/pizzas/new_comment.html
{% extends "pizzas/base.html" %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/new_comment.css' %}">
</head>

<body>
    <div class="form-container">
        <h2 class="pizza-name">
            <a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a>
        </h2>

        <p class="title">Add a new comment: </p>
        <div class="form">
            <form action="{% url 'pizzas:new_comment' pizza.id %}" method='post'>
                {% csrf_token %}
                {{ form.as_p }}
                {{ form.name.errors }}
            </form>
            <button class="form-button" name="submit">Add comment</button>
        </div>
    </div>

</body>

</html>


{% endblock content %}

pizzas/templates/pizzas/pizza.html
{% extends "pizzas/base.html" %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/pizza.css' %}">
</head>

<body>

    <div class="pizza-body">
        <div class="image-container">
            <h2 class="pizza-name">{{ pizza.name }}</h2>
            <img class="pizza-image" src="{{pizza.thumb.url}}">
        </div>
        <div class="info-container">
            <h2>Available Toppings:</h2>
            <ul>
                {% for t in toppings %}

                <li>{{ t.name|linebreaks }}</li>

                {% empty %}

                <li>There are no toppings on this pizza.</li>

                {% endfor %}

            </ul>
            <ul>
                {% for c in comments %}

                <li>{{ c.name|linebreaks }}</li>

                {% empty %}

                <h2>There are no reviews for this pizza.</h2>

                {% endfor %}

            </ul>
            <div class="button">
                <a href="{% url 'pizzas:new_comment' pizza.id %}">Add a comment</a>
            </div>
        </div>
    </div>

</body>

</html>



{% endblock content %}

pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'css/pizzas.css' %}">
    <title>Pizzas</title>
</head>

<body>
    <h2 class="pizza-title">Our Available Pizzas</h2>

    <ul class="available-pizzas">
        {% for pizza in pizzas %}
        <div class="available-pizza">
            <li class="cards_item"><a class="link" href="{% url 'pizzas:pizza' pizza.id %}">
                    {{ pizza }}
                </a></li>
            <img class="image" src="{{pizza.thumb.url}}">
        </div>
        {% empty %}
        <p>No pizzas have been added yet.</p>
        {% endfor %}

    </ul>

</body>

</html>



{% endblock content %}